services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:8000"
    depends_on:
      - db
      - mongodb
    env_file:
      - .env
    environment:
      ENVIRONMENT: prod
      DATABASE_URL: ${DATABASE_URL_PROD}
    volumes:
      - ./app:/app
    restart: always

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    expose:
      - "27017"

volumes:
  postgres_data:
  mongodb_data:
  app:
