import os

ENVIRONMENT = os.getenv("ENVIRONMENT", "dev")

MAX_IMAGE_PER_INVENTION = 10
BUCKET_NAME = "user-images"
MINIO_URL = os.getenv("MINIO_URL")

# Security encryption
SECRET_KEY = os.getenv('SECRET_KEY', 'dev_example')
ALGORITHM = os.getenv('ALGORITHM', 'HS256') # HS256 should be changed in future
ACESS_TOKEN_EXPIRATION_MINUTES = 60

ROOT_PATH_URL = os.getenv('ROOT_PATH_URL', "")

MONGO_URL = os.environ.get("MONGO_URL")

DATABASE_URL = os.getenv("DATABASE_URL")
DATABASE_URL_ALEMBIC = os.getenv("DATABASE_URL_ALEMBIC")

MINIO_LOGIN = os.getenv('MINIO_LOGIN')
MINIO_PASSWORD = os.getenv('MINIO_PASSWORD')
MINIO_CONTAINER_URL = os.getenv('MINIO_CONTAINER_URL')

INITIAL_ADMIN_USERNAME = os.getenv("INITIAL_ADMIN_USERNAME")
INITIAL_ADMIN_PASSWORD = os.getenv("INITIAL_ADMIN_PASSWORD")
INITIAL_ADMIN_NAME = os.getenv("INITIAL_ADMIN_NAME")
INITIAL_ADMIN_EMAIL = os.getenv("INITIAL_ADMIN_EMAIL")