version: 1
disable_existing_loggers: False
formatters:
  custom:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  default:
    class: logging.StreamHandler
    formatter: custom
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [default]
    level: INFO
  uvicorn.error:
    handlers: [default]
    level: INFO
    propagate: False
  uvicorn.access:
    handlers: [default]
    level: INFO
    propagate: False
root:
  handlers: [default]
  level: INFO
