"""empty message

Revision ID: 158fd426371f
Revises: 582e64f4601d
Create Date: 2025-06-05 14:57:48.152294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '158fd426371f'
down_revision: Union[str, None] = '582e64f4601d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_username', 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
