"""create_invention

Revision ID: 289bb502f9e9
Revises: d0a95da65a06
Create Date: 2025-06-24 18:49:07.868244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '289bb502f9e9'
down_revision: Union[str, None] = 'd0a95da65a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invention',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('situacao', sa.Enum('arquivado', 'arquivado_definitivamente', 'concedido_registrado', 'indeferido', 'numeracao_anulada', 'pedido_de_protecao_depositado', 'rejeitado', 'titularidade_transferida', name='inventionstatustype'), nullable=False),
    sa.Column('trl', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('desenho_industrial', 'marca', 'modelo_de_utilidade', 'patente_de_invencao', 'programa_de_computador', name='inventiontype'), nullable=False),
    sa.Column('data_submissao', sa.Date(), nullable=False),
    sa.CheckConstraint('trl > 0 and trl < 10', name='ch0_invention_trl'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo', 'type', name='uq0_invention')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invention')
    # ### end Alembic commands ###
