"""remove_id_user_pk_ticket

Revision ID: 4c80f5706c30
Revises: 9eca58bd7eed
Create Date: 2025-07-14 22:27:16.498431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c80f5706c30'
down_revision: Union[str, None] = '9eca58bd7eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    laboratory_status_type = sa.Enum(
        'accepted', 'rejected', 'on_hold',
        name='laboratorystatustype'
    )
    laboratory_status_type.create(op.get_bind())
    op.add_column('laboratory', sa.Column('status',  laboratory_status_type, nullable=False))
    op.alter_column('laboratory', 'id_user',
               existing_type=sa.UUID(),
               nullable=False)

    op.drop_constraint('ticket_pkey', 'ticket', type_='primary')
    op.create_primary_key('ticket_pkey', 'ticket', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laboratory', 'id_user',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('laboratory', 'status')

    op.drop_constraint('ticket_pkey', 'ticket', type_='primary')
    op.create_primary_key('ticket_pkey', 'ticket', ['id', 'id_user'])
    # ### end Alembic commands ###
