"""change_invention_id_unit

Revision ID: 4d5c62a3f5e6
Revises: 4c80f5706c30
Create Date: 2025-07-20 12:02:20.823203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d5c62a3f5e6'
down_revision: Union[str, None] = '4c80f5706c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invention', sa.Column('id_unit', sa.Uuid(), nullable=False))
    op.drop_constraint('invention_id_unity_fkey', 'invention', type_='foreignkey')
    op.create_foreign_key(None, 'invention', 'unit', ['id_unit'], ['id'])
    op.drop_column('invention', 'id_unity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invention', sa.Column('id_unity', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invention', type_='foreignkey')
    op.create_foreign_key('invention_id_unity_fkey', 'invention', 'unit', ['id_unity'], ['id'])
    op.drop_column('invention', 'id_unit')
    # ### end Alembic commands ###
