"""add_tabela_owner_invention

Revision ID: 50830ee96d3b
Revises: c7c9e8c02d1a
Create Date: 2025-07-07 13:49:29.172077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50830ee96d3b'
down_revision: Union[str, None] = 'c7c9e8c02d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('invention_owner',
    sa.Column('id_owner', sa.Uuid(), nullable=False),
    sa.Column('id_invention', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_invention'], ['invention.id'], ),
    sa.ForeignKeyConstraint(['id_owner'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id_owner', 'id_invention')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invention_owner')
    op.drop_table('owner')
    # ### end Alembic commands ###
