"""empty message

Revision ID: 582e64f4601d
Revises: 0de7ad63e4e8
Create Date: 2025-06-04 17:13:28.079059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '582e64f4601d'
down_revision: Union[str, None] = '0de7ad63e4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    op.create_unique_constraint('user_email_key', 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
