"""add_nullable_id_user_lab

Revision ID: 6d3ff36322a4
Revises: 9794a6f5f87f
Create Date: 2025-07-07 22:33:31.830952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d3ff36322a4'
down_revision: Union[str, None] = '9794a6f5f87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laboratory', 'id_user',
               existing_type=sa.UUID(), # Ou sa.UUID, dependendo do seu DB
               nullable=True,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laboratory', 'id_user',
               existing_type=sa.UUID(), # Ou sa.UUID
               nullable=False,
               existing_nullable=True)
    # ### end Alembic commands ###
