"""change_id_unity

Revision ID: 9794a6f5f87f
Revises: e04df48600db
Create Date: 2025-07-07 22:29:22.127869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9794a6f5f87f'
down_revision: Union[str, None] = 'e04df48600db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratory', sa.Column('id_unit', sa.Uuid(), nullable=False))
    op.drop_constraint('laboratory_id_unity_fkey', 'laboratory', type_='foreignkey')
    op.create_foreign_key(None, 'laboratory', 'unit', ['id_unit'], ['id'])
    op.drop_column('laboratory', 'id_unity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratory', sa.Column('id_unity', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'laboratory', type_='foreignkey')
    op.create_foreign_key('laboratory_id_unity_fkey', 'laboratory', 'unit', ['id_unity'], ['id'])
    op.drop_column('laboratory', 'id_unit')
    # ### end Alembic commands ###
