"""lab_member_and_change_ticket

Revision ID: 9eca58bd7eed
Revises: 6d3ff36322a4
Create Date: 2025-07-08 15:06:48.795872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9eca58bd7eed'
down_revision: Union[str, None] = '6d3ff36322a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_laboratory', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_laboratory'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_laboratory')
    )
    op.create_unique_constraint('uq0_owner', 'owner', ['nome'])

    op.drop_constraint('ticket_pkey', 'ticket', type_='primary')
    op.create_primary_key('ticket_pkey', 'ticket', ['id', 'id_user'])
    op.alter_column('ticket', 'id_tecnologia_alvo',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'id_tecnologia_alvo',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('uq0_owner', 'owner', type_='unique')
    op.drop_table('lab_member')
    op.drop_constraint('ticket_pkey', 'ticket', type_='primary')
    op.create_primary_key('ticket_pkey', 'ticket', ['id', 'id_user', 'id_tecnologia_alvo'])
    # ### end Alembic commands ###
