"""add_tabela_inventor_invention

Revision ID: a1088601de5d
Revises: 50830ee96d3b
Create Date: 2025-07-07 18:48:20.734452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1088601de5d'
down_revision: Union[str, None] = '50830ee96d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventor_invention',
    sa.Column('id_inventor', sa.Uuid(), nullable=False),
    sa.Column('id_invention', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_invention'], ['invention.id'], ),
    sa.ForeignKeyConstraint(['id_inventor'], ['inventor.id'], ),
    sa.PrimaryKeyConstraint('id_inventor', 'id_invention')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventor_invention')
    op.drop_table('inventor')
    # ### end Alembic commands ###
