"""add_tabela_unit

Revision ID: b50808761eeb
Revises: 289bb502f9e9
Create Date: 2025-07-07 13:27:08.347837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b50808761eeb'
down_revision: Union[str, None] = '289bb502f9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sigla', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('insituto', 'faculdade', 'escola', 'secretaria', 'pro_reitoria', name='unittype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'sigla', name='uq0_unit')
    )
    op.add_column('invention', sa.Column('id_unity', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'invention', 'unit', ['id_unity'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invention', type_='foreignkey')
    op.drop_column('invention', 'id_unity')
    op.drop_table('unit')
    # ### end Alembic commands ###
