"""add_tabela_laboratory

Revision ID: c7c9e8c02d1a
Revises: b50808761eeb
Create Date: 2025-07-07 13:35:00.599687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7c9e8c02d1a'
down_revision: Union[str, None] = 'b50808761eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_unity', sa.Uuid(), nullable=False),
    sa.Column('id_user', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sigla', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('resumo', sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=False),
    sa.Column('condicao_de_uso', sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=False),
    sa.ForeignKeyConstraint(['id_unity'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'sigla', name='uq0_laboratory')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laboratory')
    # ### end Alembic commands ###
