"""add_tabela_ticketn

Revision ID: e04df48600db
Revises: a1088601de5d
Create Date: 2025-07-07 19:02:11.996774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e04df48600db'
down_revision: Union[str, None] = 'a1088601de5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_user', sa.Uuid(), nullable=False),
    sa.Column('id_tecnologia_alvo', sa.Uuid(), nullable=False),
    sa.Column('nome_do_projeto', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'on_hold', name='ticketstatustype'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_user', 'id_tecnologia_alvo'),
    sa.UniqueConstraint('nome_do_projeto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
