name: Deploy via Webhook

on:
  push:
    branches:
      - main

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar POST para webhook
        run: |
          curl -X POST '${{ secrets.DEPLOY_URL_WEBHOOK }}' \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}"
